# Exercise 3. - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  

Check out [Alcohol Consumption Exercises Video Tutorial](https://youtu.be/az67CMdmS6s) to watch a data scientist go through the exercises


### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [7]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv'
drinks = pd.read_csv(url)
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [12]:
# Illia
drinks.sort_values(by='beer_servings').tail(1)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
117,Namibia,376,3,1,6.8,AF

### Step 5. For each continent print the statistics for wine consumption.

In [ ]:
# Mateusz

### Step 6. Print the mean alcohol consumption per continent for every column

In [ ]:
# Kuba
drinks.groupby("continent").mean(numeric_only=True)

### Step 7. Print the median alcohol consumption per continent for every column

In [ ]:
# Kuba
drinks.groupby("continent").median(numeric_only=True)

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [ ]:
# Piotr
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max'])